-- QuartzWatch Tables
-- 节点注册表
CREATE TABLE IF NOT EXISTS QRTZ_WATCH_NODES (
    NODE_ID VARCHAR(255) NOT NULL,
    METADATA TEXT,
    LAST_HEARTBEAT BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    PRIMARY KEY (NODE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 分片分配表
CREATE TABLE IF NOT EXISTS QRTZ_WATCH_SHARDS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    JOB_KEY VARCHAR(255) NOT NULL,
    NODE_ID VARCHAR(255) NOT NULL,
    SHARD_DATA TEXT,
    CREATED_TIME BIGINT,
    PRIMARY KEY (ID),
    INDEX IDX_JOB_KEY (JOB_KEY),
    INDEX IDX_NODE_ID (NODE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Misfire记录表
CREATE TABLE IF NOT EXISTS QRTZ_WATCH_MISFIRE_LOG (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    JOB_KEY VARCHAR(255) NOT NULL,
    NODE_ID VARCHAR(255),
    SCHEDULED_TIME BIGINT,
    ACTUAL_TIME BIGINT,
    DELAY_MS BIGINT,
    RETRY_COUNT INT DEFAULT 0,
    STATUS VARCHAR(20),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX IDX_JOB_KEY (JOB_KEY),
    INDEX IDX_CREATED_TIME (CREATED_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 作业执行历史表
CREATE TABLE IF NOT EXISTS QRTZ_WATCH_JOB_HISTORY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    JOB_KEY VARCHAR(255) NOT NULL,
    NODE_ID VARCHAR(255),
    SHARD_INDEX INT,
    START_TIME BIGINT,
    END_TIME BIGINT,
    DURATION_MS BIGINT,
    STATUS VARCHAR(20),
    ERROR_MESSAGE TEXT,
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    INDEX IDX_JOB_KEY (JOB_KEY),
    INDEX IDX_START_TIME (START_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 